-- 1. Create the properties table
create table public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  price text not null,
  location text not null,
  beds integer,
  baths integer,
  area text,
  image text,
  type text check (type in ('Sale', 'Rent')),
  category text check (category in ('Land', 'Villa', 'House', 'Apartment')),
  description text,
  images text[],
  features text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the storage bucket for images
-- Note: You might need to create the bucket 'property-images' manually in the dashboard if this fails, 
-- but usually you can insert into storage.buckets if you have permissions.
-- Better to just instruct user to create bucket 'property-images' and set it to public.

insert into storage.buckets (id, name, public) 
values ('property-images', 'property-images', true)
on conflict (id) do nothing;

-- 3. Set up Row Level Security (RLS) policies
-- Enable RLS
alter table public.properties enable row level security;

-- Policy to allow anyone to READ properties (SELECT)
create policy "Allow public read access"
  on public.properties
  for select
  to public
  using (true);

-- Policy to allow authenticated users (service_role or authenticated) to INSERT/UPDATE/DELETE
-- For this simple app without real user auth integration on Supabase side yet,
-- and since we use the admin login which is local.
-- To keep it simple for now, we will allow ALL operations for anon (public) BUT
-- effectively we only protect the admin pages via middleware.
-- IN PRODUCTION: You should enable proper RLS and use Supabase Auth.
-- FOR DEMO/MVP: We will allow anon to insert/update/delete so our local admin works without full Supabase Auth integration.

create policy "Allow public insert/update/delete for demo"
  on public.properties
  for all
  to public
  using (true)
  with check (true);

-- 4. Storage Policies
-- Allow public access to view images
create policy "Give public access to images"
  on storage.objects
  for select
  to public
  using (bucket_id = 'property-images');

-- Allow public access to upload images (for our admin panel)
create policy "Allow upload to property-images"
  on storage.objects
  for insert
  to public
  with check (bucket_id = 'property-images');

-- Allow public access to delete images
create policy "Allow delete from property-images"
  on storage.objects
  for delete
  to public
  using (bucket_id = 'property-images');
